apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: exam-server
data:
  pgbouncer.ini: |
    [databases]
    write_db = host=postgres-0.postgres-service.exam-server.svc.cluster.local dbname=exam_server_BD user=postgres password=postgres123
    read_db  = host=postgres-1.postgres-service.exam-server.svc.cluster.local dbname=exam_server_BD user=postgres password=postgres123

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = 5432
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = transaction
    max_client_conn = 100
    default_pool_size = 20

  userlist.txt: |
    "postgres" "md5163311300b0732b814a34aabfdfffe62"
