apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: exam-server
data:
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                 METHOD
    local   all             all                                     trust
    host    all             all             127.0.0.1/32            trust
    host    all             all             ::1/128                 trust
    # Allow replication from any pod inside the cluster
    host    replication     replica         0.0.0.0/0               trust
    host    replication     replica         ::/0                    trust